// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUserNotFound(err error) bool {
	e := errors.FromError(err)
	return e.Reason == RecipeFrontendError_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, RecipeFrontendError_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsContentMissing(err error) bool {
	e := errors.FromError(err)
	return e.Reason == RecipeFrontendError_CONTENT_MISSING.String() && e.Code == 400
}

func ErrorContentMissing(format string, args ...interface{}) *errors.Error {
	return errors.New(400, RecipeFrontendError_CONTENT_MISSING.String(), fmt.Sprintf(format, args...))
}

func IsIncorrectPassword(err error) bool {
	e := errors.FromError(err)
	return e.Reason == RecipeFrontendError_INCORRECT_PASSWORD.String() && e.Code == 200
}

func ErrorIncorrectPassword(format string, args ...interface{}) *errors.Error {
	return errors.New(200, RecipeFrontendError_INCORRECT_PASSWORD.String(), fmt.Sprintf(format, args...))
}

func IsInternalServerError(err error) bool {
	e := errors.FromError(err)
	return e.Reason == RecipeFrontendError_INTERNAL_SERVER_ERROR.String() && e.Code == 500
}

func ErrorInternalServerError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, RecipeFrontendError_INTERNAL_SERVER_ERROR.String(), fmt.Sprintf(format, args...))
}
