// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/exuan/ruber/app/recipe/frontend/internal/biz"
	"github.com/exuan/ruber/app/recipe/frontend/internal/conf"
	"github.com/exuan/ruber/app/recipe/frontend/internal/server"
	"github.com/exuan/ruber/app/recipe/frontend/internal/service"
	"github.com/exuan/ruber/pkg/provider"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, string2 string, redisConfig *provider.RedisConfig, attachmentConfig *provider.AttachmentConfig, logger log.Logger) (*kratos.App, func(), error) {
	discovery := provider.NewDiscovery(string2)
	recipeClient := provider.NewRecipeServiceClient(discovery)
	userClient := provider.NewUserServiceClient(discovery)
	client, cleanup, err := provider.NewRedis(redisConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	attachment, err := provider.NewAttachment(attachmentConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	frontend := biz.NewFrontend(recipeClient, userClient, logger, client, attachment)
	frontendService := service.NewFrontendService(frontend, logger)
	httpServer := server.NewHTTPServer(confServer, frontendService, client, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
