// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RbUserColumns holds the columns for the "rb_user" table.
	RbUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
		{Name: "nickname", Type: field.TypeString},
		{Name: "avatar", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "salt", Type: field.TypeString},
		{Name: "owner", Type: field.TypeString},
		{Name: "app", Type: field.TypeString, Default: ""},
		{Name: "properties", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeInt, Default: 0},
		{Name: "creator", Type: field.TypeString},
		{Name: "modifier", Type: field.TypeString},
		{Name: "update_time", Type: field.TypeInt64},
		{Name: "create_time", Type: field.TypeInt64},
	}
	// RbUserTable holds the schema information for the "rb_user" table.
	RbUserTable = &schema.Table{
		Name:       "rb_user",
		Columns:    RbUserColumns,
		PrimaryKey: []*schema.Column{RbUserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RbUserTable,
	}
)

func init() {
	RbUserTable.Annotation = &entsql.Annotation{
		Table: "rb_user",
	}
}
