// Code generated by entc, DO NOT EDIT.

package favorite

const (
	// Label holds the string label denoting the favorite type in the database.
	Label = "favorite"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRecipeID holds the string denoting the recipe_id field in the database.
	FieldRecipeID = "recipe_id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the favorite in the database.
	Table = "rb_recipe_favorite"
)

// Columns holds all SQL columns for favorite fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldRecipeID,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() int64
)
